In [2]:
import pandas as pd

In [3]:
sold = pd.read_csv("sold_combined.csv")
listed = pd.read_csv("listed_combined.csv")

/var/folders/tl/nq7m6l0d7g3_80l5ngq1x0t00000gn/T/ipykernel_70012/3516636363.py:1: DtypeWarning: Columns (0,1,4,78,79,80,82,83) have mixed types. Specify dtype option on import or set low_memory=False.
  sold = pd.read_csv("sold_combined.csv")
/var/folders/tl/nq7m6l0d7g3_80l5ngq1x0t00000gn/T/ipykernel_70012/3516636363.py:2: DtypeWarning: Columns (43) have mixed types. Specify dtype option on import or set low_memory=False.
  listed = pd.read_csv("listed_combined.csv")

In [4]:
sold

,BuyerAgentAOR,ListAgentAOR,Flooring,ViewYN,WaterfrontYN,BasementYN,PoolPrivateYN,OriginalListPrice,ListingKey,ListAgentEmail,...,PostalCode,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,OriginatingSystemName,OriginatingSystemSubName,BuyerAgencyCompensationType,BuyerAgencyCompensation,latfilled,lonfilled
0,Mlslistings,Mlslistings,"Carpet,Tile,Wood",True,NaN,NaN,False,499000.0,551985747,jwachter@cbnorcal.com,...,94401,6472.0,NaN,NaN,CRMLS,CRMLS_MLSL,NaN,NaN,NaN,NaN
1,HighDesert,HighDesert,NaN,NaN,NaN,NaN,NaN,0.0,535486633,eabrown@lee-associates.com,...,92394,NaN,52320.0,NaN,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN
2,OrangeCounty,OrangeCounty,NaN,True,NaN,NaN,NaN,75000.0,529986282,Joe@9WINWIN.com,...,93240,NaN,217364.0,NaN,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN
3,InlandValleys,InlandValleys,NaN,True,NaN,NaN,NaN,199000.0,529618166,carolthefinder@yahoo.com,...,92308,NaN,217800.0,NaN,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN
4,SouthwestRiversideCounty,SouthwestRiversideCounty,NaN,True,NaN,NaN,NaN,19500.0,522614340,jtavisola@tavisola.com,...,93544,0.0,108883.0,NaN,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
549077,LakeCounty,LakeCounty,NaN,True,NaN,NaN,NaN,22500.0,1015632519,davidlucido@yahoo.com,...,95451,NaN,13006.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
549078,SierraNorthValley,SierraNorthValley,NaN,NaN,NaN,NaN,NaN,800000.0,551875927,jen.spaletta@c21selectgroup.com,...,96021,NaN,161607.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN
549079,SanDiego,SanDiego,"Carpet,Tile,Wood",True,NaN,NaN,False,4500.0,512397297,Carla@PacificShoreProperties.com,...,92014,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
549080,SanDiego,SanDiego,Carpet,True,NaN,NaN,False,1900.0,445618495,jaimebea.ccr@gmail.com,...,91932,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
549081,SanDiego,SanDiego,NaN,False,NaN,NaN,False,1650000.0,421775918,lesliero@hotmail.com,...,92103,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
listed

,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,...,MainLevelBedrooms,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,BuyerOfficeName.1,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,UnparsedAddress.1
0,90000.0,1075010398,miriamlara03@gmail.com,NaN,NaN,Miriam,Lara,34.097939,-117.909653,1045 N Azusa 61,...,NaN,NaN,2.0,Covina Valley Unified,91722,NaN,0.0,NaN,NaN,1045 N Azusa 61
1,1500000.0,1074974457,janelle@judsonre.com,NaN,NaN,Janelle,Judson,33.121241,-117.081614,NaN,...,NaN,NaN,NaN,NaN,92025,NaN,0.0,NaN,NaN,NaN
2,1340000.0,1074973329,haleh360@Gmail.com,NaN,NaN,Haleh,Dowlatshahi,34.052207,-118.408445,2220 Avenue Of The Stars 2704,...,NaN,False,NaN,NaN,90067,NaN,2105.0,177861.0,NaN,2220 Avenue Of The Stars 2704
3,2500000.0,1074954552,Reneechen@yourhomesoldguaranteed.com,NaN,NaN,Renee,Chen,33.496363,-117.691677,16 Palisades,...,0.0,False,3.0,Capistrano Unified,92677,NaN,254.0,5300.0,NaN,16 Palisades
4,3150000.0,1074936537,anader@dppre.com,NaN,NaN,Margaret,Nader,34.119345,-118.111254,1615 Waverly Road,...,NaN,NaN,2.0,NaN,91108,NaN,NaN,9404.0,NaN,1615 Waverly Road
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
782532,790000.0,1114826339,gabe@gabemendez.realtor,NaN,NaN,Gabriel,Mendez,32.678852,-117.038393,7089 wattle drive,...,NaN,NaN,0.0,San Diego Unified,92139,NaN,338.0,NaN,NaN,7089 wattle drive
782533,3000.0,1112960460,MikeJonesSanDiegoRealtor@Gmail.com,NaN,NaN,Mike,Jones,32.775552,-117.252444,725 Kingston Court,...,NaN,NaN,0.0,San Diego Unified,92109,NaN,0.0,2297.0,NaN,725 Kingston Court
782534,705500.0,1112557556,maryvillamarhomes@gmail.com,NaN,NaN,Mary,Villalobos,32.597096,-117.054329,22 Connoley Circle,...,3.0,False,2.0,Sweetwater Union,91911,NaN,0.0,4890.0,NaN,22 Connoley Circle
782535,425000.0,1109207214,frank@frankhuerta.com,NaN,NaN,Frank,Huerta,33.285277,-117.100306,31844 Patrick Way,...,NaN,NaN,NaN,NaN,92082,NaN,0.0,202554.0,NaN,31844 Patrick Way
782536,8000.0,1053992017,mercedes@staycoronado.com,NaN,NaN,Mercedes,Estrada,32.699671,-117.172576,1099 1st 103,...,NaN,NaN,0.0,Coronado Unified,92118,NaN,NaN,4411.0,NaN,1099 1st 103